packages:
  - apps/**
  - libs/**
  - projects/**
verifyDepsBeforeRun: false
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@rt-tools/core@0.0.5 || 0.1.0'
  - '@rt-tools/store@0.0.6 || 0.0.8 || 0.1.0'
  - '@rt-tools/utils@0.0.7 || 0.0.9 || 0.1.0 || 0.1.1 || 0.2.0'
