/**
 * Английский набор подписей админки.
 *
 * Ключи те же, что у русского набора: один ключ на оба языка — разные ключи под один текст
 * расходятся молча, набор переводят, а экран берёт соседний.
 *
 * Набор полон, и это сказано типом: `Record` вместо `Partial<Record>` требует текста на каждый
 * ключ русского набора, и ключ, заведённый только с одной стороны, не собирается вовсе. Прежде
 * набор был неполон намеренно — экраны переводились задачами эпика по одному, — и ключ без
 * перевода был виден на экране признаком ненайденного ключа.
 */
import { ERefusal } from '@rt/message-bus-common';

import { TAdminLabelKey } from './admin-labels';

/** Подписи админки по-английски. Ключ читается в шаблоне, значение правится здесь. */
export const ADMIN_LABELS_EN: Record<TAdminLabelKey, string> = Object.freeze({
    appTitle: 'Message bus',
    navSections: 'Sections',
    signOut: 'Sign out',
    theme: 'Theme',
    language: 'Language',
    languageSwitch: 'Label language',
    signInTitle: 'Admin sign-in',
    signInTab: 'Sign in',
    signInName: 'Account',
    signInNameHint: 'The name of a project or of the owner',
    signInPassword: 'Password',
    signInPasswordHint: 'The password of the account',
    signInSubmit: 'Sign in',
    signInFaultPair: 'The name or the password did not match',
    signInFaultForm: 'Fill in the name and the password',
    signInFaultService: 'The receiver did not answer. Try again',
    setupTitle: 'First record',
    setupHint: 'The receiver holds no records yet. The first one gets every right; these name and password sign you in at once.',
    setupName: 'Name',
    setupPassword: 'Password',
    setupSubmit: 'Create',
    setupFailed: 'The first record could not be created',
    noSectionsTitle: 'No section is open to you',
    noSectionsFrom: 'Rights are given by the owner of the receiver — ask them to open the sections you need',

    sectionPostmortems: 'Incident analyses',
    sectionProposals: 'Proposals',
    sectionSummaries: 'Project digests',
    sectionInvites: 'Invitations',
    sectionPeople: 'People',
    sectionUsage: 'Usage',
    sectionChat: 'Chat',
    hintChat: 'The talks of the site visitors: the operator reads them and answers from one screen',
    chatTalksEmpty: 'There are no talks',
    chatTalksEmptyFrom: 'The talks of the sites you answer for will appear here',
    chatFeedUnchosen: 'Choose a talk on the left',
    chatAnswerPlaceholder: 'An answer to the visitor',
    chatAnswerSend: 'Send',
    chatAnswerRefused: 'The remark did not go',
    chatSideVisitor: 'Visitor',
    chatSideOperator: 'Operator',
    chatStateLive: 'Live',
    chatStateClosed: 'Closed',
    chatClose: 'Close the talk',
    chatReopen: 'Open again',
    chatFilterSite: 'Site',
    chatFilterSiteAll: 'All sites',

    hintPostmortems: 'What broke in the projects and why — one analysis per incident',
    hintProposals: 'What the projects propose to change in the rules layer',
    hintSummaries: 'A digest of one project for a calendar month — one record per pair',
    hintInvites: 'How a project connects itself. Issued here by the button «Invite a project»',
    hintPeople: 'Who signs in to the receiver, with which role and when they last did',
    hintUsage: 'Which rules, patterns and skills a project loads in its sessions — one row per skill for the period',

    filterTree: 'Project',
    filterTreeAll: 'All projects',
    filterState: 'State',
    filterStateAll: 'All states',
    filterVersionAll: 'All versions',
    filterVersionNone: 'Without a version',
    filterPeriodFrom: 'From',
    filterPeriodTo: 'To',

    columnTree: 'Project',
    columnFile: 'File',
    columnArrivedAt: 'Arrived',
    columnUpdatedAt: 'Updated',
    columnResource: 'Resource',
    columnAddress: 'Address',
    columnMonth: 'Month',
    columnSessions: 'Sessions',
    columnRanAt: 'Run',
    columnInviteName: 'Project name',
    columnInviteState: 'State',
    columnIssuedAt: 'Issued',
    columnExpiresAt: 'Valid until',
    columnInviteTree: 'Created project',
    columnPersonName: 'Name',
    columnPersonRole: 'Role',
    columnPersonState: 'State',
    columnLastLoginAt: 'Last sign-in',
    columnState: 'State',
    columnSkill: 'Skill',
    columnKind: 'Kind',
    columnLoads: 'Loads',
    columnUsageSessions: 'Sessions',
    columnDenials: 'Denials',
    columnDay: 'Day',
    columnSession: 'Session',
    columnCount: 'Times',
    kindRule: 'rule',
    kindPattern: 'pattern',
    kindSkill: 'skill of the package',
    kindOwn: 'own skill of the project',
    digestLoadsByDay: 'Loads by day',
    digestTopSkills: 'Top skills',
    digestKinds: 'By kind',
    digestDenials: 'Denials of the gate',
    digestEmpty: 'There were no loads over the period',
    digestNoDenials: 'There were no denials over the period',
    digestFailed: 'The digest of the period could not be read',
    quickPeriodAria: 'Quick choice of the period',
    quickPeriod7: '7 days',
    quickPeriod30: '30 days',
    quickPeriod90: '90 days',
    releaseVersion: 'In which version',
    quarantineNote: 'What is disputed',

    closedByPublisher: 'closed by the publisher',

    cargoStateNew: 'New',
    cargoStateInWork: 'In work',
    cargoStateFixed: 'Done',
    cargoStateReleased: 'Released',
    cargoStateQuarantined: 'In quarantine',

    inviteStateWaiting: 'Waiting',
    inviteStateRedeemed: 'Redeemed',
    inviteStateExpired: 'Expired',
    inviteStateRevoked: 'Revoked',

    inviteCreate: 'Invite a project',
    inviteCreateTitle: 'An invitation to a project',
    inviteCreateName: 'The name of the future project',
    inviteCreateNameHint: 'By it the project will be seen in the lists. It cannot be changed later.',
    inviteCreateSubmit: 'Issue',
    inviteCreateWarn: 'The code appears here once: there will be nowhere to show it a second time.',
    inviteCreateCode: 'The code of the invitation',
    inviteCreateCopy: 'Copy',
    inviteCreateCopied: 'The code is copied',
    inviteCreateExpires: 'Valid until {{until}}',
    inviteCreateDone: 'The invitation for «{{name}}» is issued',
    inviteCreateFailed: 'The invitation could not be issued',
    inviteCreateClose: 'Close',
    inviteRevoke: 'Revoke',
    inviteRevokeTitle: 'Revoke the invitation',
    inviteRevokeQuestion: 'The invitation for «{{name}}» stops working. It cannot be brought back: the project will need a new one.',
    inviteRevokeDone: 'The invitation for «{{name}}» is revoked',
    inviteRevokeFailed: 'The invitation could not be revoked',

    personRoleNone: 'No role',
    personStateLive: 'Active',
    personStateDisabled: 'Disabled',
    personNeverLoggedIn: 'Never signed in',
    personCreate: 'Create a user',
    personCreateTitle: 'A new user',
    personCreateName: 'Name',
    personCreateNameHint: 'The user signs in by it. It cannot be changed later.',
    personCreatePassword: 'The first password',
    personCreatePasswordHint: 'Hand it to the user yourself: the receiver neither shows a password nor sends it out.',
    personCreateSubmit: 'Create',
    personCreateDone: 'The user «{{name}}» is created',
    personCreateFailed: 'The user could not be created',
    personPasswordTitle: 'A new password',
    personPasswordFor: 'The user «{{name}}»',
    personPasswordField: 'A new password',
    personPasswordHint: 'The previous password stops being accepted at once; the open sessions of the user stay.',
    personPasswordSubmit: 'Change',
    personPasswordDone: 'The password of the user «{{name}}» is changed',
    personPasswordFailed: 'The password could not be changed',
    personPasswordMenu: 'Change the password',
    personDisable: 'Disable',
    personDisableTitle: 'Disable the user',
    personDisableQuestion:
        'The user «{{name}}» will not sign in any more, and their open sessions break. The record cannot be brought back: a new one will be needed.',
    personDisableDone: 'The user «{{name}}» is disabled',
    personDisableFailed: 'The user could not be disabled',
    personAccessMenu: 'Rights',
    personAccessTitle: 'Rights: {{name}}',
    personAccessRole: 'Role',
    personAccessRoleNone: 'Without a role',
    personAccessRoleHint: 'The rights of the role are the base. Below, any right is given to or taken from this user personally.',
    personAccessRights: 'Rights',
    personAccessByRole: 'By the role',
    personAccessGranted: 'Given',
    personAccessRevoked: 'Taken',
    personAccessHas: 'yes',
    personAccessHasNot: 'no',
    personAccessSubmit: 'Save',
    personAccessDone: 'The rights of the user «{{name}}» are saved',
    personAccessFailed: 'The rights could not be saved',
    panelClose: 'Close',

    sectionRoles: 'Roles',
    hintRoles: 'What each role opens and how many users hold it',
    columnRoleName: 'Role',
    columnRoleRights: 'Rights',
    columnRolePeople: 'Users',
    roleRightsNone: 'Not a single right',
    roleCreate: 'Create a role',
    roleCreateTitle: 'A new role',
    roleEditTitle: 'Role',
    roleName: 'Name',
    roleNameHint: 'This is how the role is seen in the list and in the rights panel of a user.',
    roleRights: 'Rights',
    roleCreateSubmit: 'Create',
    roleSaveSubmit: 'Save',
    roleCreateDone: 'The role «{{name}}» is created',
    roleCreateFailed: 'The role could not be created',
    roleSaveDone: 'The role «{{name}}» is saved',
    roleSaveFailed: 'The role could not be saved',
    roleEditMenu: 'Change',
    roleDelete: 'Delete',
    roleDeleteTitle: 'Delete the role',
    roleDeleteQuestion: 'The role «{{name}}» will be deleted. Nobody holds it; it cannot be brought back — only created anew.',
    roleDeleteDone: 'The role «{{name}}» is deleted',
    roleDeleteFailed: 'The role could not be deleted',
    rightRead: 'reading',
    rightManage: 'editing',
    listEmptyRoles: 'There are no roles',
    listEmptyRolesFrom: 'They are created by the button «Create a role» above the list',

    listEmptyPeople: 'There are no records of people',
    listEmptyPeopleFrom: 'They are created by the button «Create a user» above the list',
    listEmptyInvites: 'There are no invitations',
    listEmptyInvitesFrom: 'They are issued by the button «Invite a project» above the list',
    listEmpty: 'There are no records',
    listEmptyFrom: 'Not a single project has sent any yet',
    listEmptyByFilter: 'There are no records under this filter',
    listEmptyByFilterFrom: 'Drop the filter above the list or choose another value in it',
    listFailed: 'It could not be read',
    listSessionEnded: 'The session has ended: sign in again',
    listColumns: 'Set up the columns',
    listRefresh: 'Read anew',
    listRetry: 'Repeat',
    listIncident: 'Incident {{incident}}',

    detailsMissing: 'There is no record: it could have been deleted',
    detailsFailed: 'The record could not be read',
    detailsClose: 'Close',
    detailsPostmortem: 'The analysis of an incident',
    detailsProposal: 'Proposal',
    detailsText: 'Text',
    detailsFixNote: 'How it was fixed',
    detailsMonthRecord: 'The record of a month',
    detailsSummary: 'Digest',
    detailsSummaryMissing: 'There was no digest in this month: the record was created by another kind of cargo',
    detailsUsageSessions: 'Sessions',
    detailsSessionsMissing: 'Over the period not a single session loaded this skill',
    detailsSessionsFailed: 'The sessions could not be read',

    // Тексты отказов приёмника: ключ — код отказа общей либы.
    [ERefusal.AccountNameTaken]: 'The account «{{name}}» already exists: the name is taken',
    [ERefusal.AccountNotFound]: 'There is no account named «{{name}}»',
    [ERefusal.AccountSelfDisable]: 'Your own account cannot be disabled: it would cut your own entry',
    [ERefusal.AccountAlreadyOff]: 'The account «{{name}}» is already disabled',
    [ERefusal.AccountGone]: 'The record disappeared between the edit and the answer',
    [ERefusal.RoleNameTaken]: 'The role «{{name}}» already exists: the name is taken',
    [ERefusal.RoleNotFound]: 'There is no role with the key «{{key}}»',
    [ERefusal.RoleHeld]: 'The role «{{name}}» is held by accounts: {{people}}. Give them another one first',
    [ERefusal.RoleRightsLost]: 'The edit would leave you without the right to the roles: give it to another account first',
    [ERefusal.RoleNameEmpty]: 'The role awaits a name',
    [ERefusal.RightUnknown]: 'The right «{{right}}» is not in the set',
    [ERefusal.RightRepeated]: 'The right «{{right}}» is named twice',
    [ERefusal.EditMalformed]: 'An edit names the right and whether it is given',
    [ERefusal.InviteNameEmpty]: 'The issue awaits the name of the future project',
    [ERefusal.InviteProjectExists]: 'The project «{{name}}» already exists: it needs no invitation, and the name is taken',
    [ERefusal.InviteAlreadyIssued]: 'A valid invitation for «{{name}}» is already issued. Revoke it to issue a new one',
    [ERefusal.InviteNotFound]: 'There is no valid invitation for «{{name}}»',
    [ERefusal.InviteRejected]: 'The invitation is not accepted',
    [ERefusal.PostmortemNotFound]: 'There is no incident analysis with that sign',
    [ERefusal.ProposalNotFound]: 'There is no proposal with that sign',
    [ERefusal.SummaryNotFound]: 'There is no record of a month with that sign',
    [ERefusal.TreeUnknown]: 'The project with the sign «{{slug}}» is unknown to the message bus',
    [ERefusal.PersonNameEmpty]: 'Creating awaits the name of the account',
    [ERefusal.PersonPasswordEmpty]: 'The account needs a password: an empty one is not accepted',
    [ERefusal.SetupClosed]: 'The first account already exists: sign in by name and password',
    [ERefusal.OwnerRoleMissing]: 'The role of the owner «{{key}}» is not in the storage: the migrations are not applied',
    [ERefusal.SignInEmpty]: 'The request carries no name or no password',
    [ERefusal.EnrollThrottled]: 'There are more requests from one client than the limit: wait and repeat',
    [ERefusal.EnrollMalformed]: 'The request awaits the code of an invitation and the sign of a project',
    [ERefusal.TreeTaken]: 'A project with that sign or that name already exists; the invitation is still valid',
    [ERefusal.SignInRequired]: 'The operation demands an entry',
    [ERefusal.RightRequired]: 'You have no right to this operation',
    [ERefusal.TreeTokenRequired]: 'The operation demands a token of a project',
    [ERefusal.TreeTokenRejected]: 'The token is not accepted',
    [ERefusal.AccessUndeclared]: 'The operation declared no access',
    [ERefusal.ChatSiteKeyEmpty]: 'The request awaits the key of the site',
    [ERefusal.ChatSiteRejected]: 'The key of the site is not accepted',
    [ERefusal.ChatOriginRejected]: 'The site accepts no requests from this address',
    [ERefusal.ChatConversationNotFound]: 'There is no conversation with that sign',
    [ERefusal.ChatTextEmpty]: 'A remark without a text is not accepted',
    [ERefusal.ChatTextTooLong]: 'The remark is longer than {{limit}} characters',
    [ERefusal.ChatThrottled]: 'There are more remarks from one visitor than {{limit}} per window: repeat in {{after}} s',
    [ERefusal.ChatStateUnknown]: 'The state of a conversation is expected as one of: live, closed',
    [ERefusal.ChatEntryRejected]: 'The page of the talks did not open',
    [ERefusal.ChatEntryStale]: 'The signature of the entry is stale',
    [ERefusal.ChatEntryExpired]: 'The entry is stale, refresh the page',
});
