/**
 * Английский набор подписей админки.
 *
 * Ключи те же, что у русского набора: один ключ на оба языка — разные ключи под один текст
 * расходятся молча, набор переводят, а экран берёт соседний.
 *
 * Набор полон, и это сказано типом: `Record` вместо `Partial<Record>` требует текста на каждый
 * ключ русского набора, и ключ, заведённый только с одной стороны, не собирается вовсе. Прежде
 * набор был неполон намеренно — экраны переводились задачами эпика по одному, — и ключ без
 * перевода был виден на экране признаком ненайденного ключа.
 */
import { ERefusal } from '@rt/message-bus-common';

import { TAdminLabelKey } from './admin-labels';

/** Подписи админки по-английски. Ключ читается в шаблоне, значение правится здесь. */
export const ADMIN_LABELS_EN: Record<TAdminLabelKey, string> = Object.freeze({
    appTitle: 'Message bus',
    navSections: 'Sections',
    signOut: 'Sign out',
    theme: 'Theme',
    language: 'Language',
    languageSwitch: 'Label language',
    noSectionsTitle: 'No section is open to you',
    noSectionsFrom: 'Rights are given by the owner of the receiver — ask them to open the sections you need',

    sectionPostmortems: 'Incident analyses',
    sectionProposals: 'Proposals',
    sectionSummaries: 'Project digests',
    sectionInvites: 'Invitations',
    sectionUsage: 'Usage',
    sectionChat: 'Chat',
    hintChat: 'The talks of the site visitors: the operator reads them and answers from one screen',
    chatTalksEmpty: 'There are no talks',
    chatTalksEmptyFrom: 'The talks of the sites you answer for will appear here',
    chatFeedUnchosen: 'Choose a talk on the left',
    chatAnswerPlaceholder: 'An answer to the visitor',
    chatAnswerSend: 'Send',
    chatAnswerRefused: 'The remark did not go',
    chatSideVisitor: 'Visitor',
    chatSideOperator: 'Operator',
    chatStateLive: 'Live',
    chatStateClosed: 'Closed',
    chatClose: 'Close the talk',
    chatReopen: 'Open again',
    chatTalkDetails: 'The talk',
    chatTalkSite: 'Site',
    chatTalkState: 'State',
    chatTalkLastMessageAt: 'Last remark',
    chatTalkUntitled: 'A talk with no remarks',
    chatFilterSite: 'Site',
    chatFilterSiteAll: 'All sites',

    hintPostmortems: 'What broke in the projects and why — one analysis per incident',
    hintProposals: 'What the projects propose to change in the rules layer',
    hintSummaries: 'A digest of one project for a calendar month — one record per pair',
    hintInvites: 'How a project connects itself. Issued here by the button «Invite a project»',
    hintUsage: 'Which rules, patterns and skills a project loads in its sessions — one row per skill for the period',

    filterTree: 'Project',
    filterTreeAll: 'All projects',
    filterState: 'State',
    filterStateAll: 'All states',
    filterVersionAll: 'All versions',
    filterVersionNone: 'Without a version',
    filterPeriodFrom: 'From',
    filterPeriodTo: 'To',

    columnTree: 'Project',
    columnFile: 'File',
    columnArrivedAt: 'Arrived',
    columnUpdatedAt: 'Updated',
    columnResource: 'Resource',
    columnAddress: 'Address',
    columnMonth: 'Month',
    columnSessions: 'Sessions',
    columnRanAt: 'Run',
    columnInviteName: 'Project name',
    columnInviteState: 'State',
    columnIssuedAt: 'Issued',
    columnExpiresAt: 'Valid until',
    columnInviteTree: 'Created project',
    columnState: 'State',
    columnSkill: 'Skill',
    columnKind: 'Kind',
    columnLoads: 'Loads',
    columnUsageSessions: 'Sessions',
    columnDenials: 'Denials',
    columnDay: 'Day',
    columnSession: 'Session',
    columnCount: 'Times',
    kindRule: 'rule',
    kindPattern: 'pattern',
    kindSkill: 'skill of the package',
    kindOwn: 'own skill of the project',
    digestLoadsByDay: 'Loads by day',
    digestTopSkills: 'Top skills',
    digestKinds: 'By kind',
    digestDenials: 'Denials of the gate',
    digestEmpty: 'There were no loads over the period',
    digestNoDenials: 'There were no denials over the period',
    digestFailed: 'The digest of the period could not be read',
    quickPeriodAria: 'Quick choice of the period',
    quickPeriod7: '7 days',
    quickPeriod30: '30 days',
    quickPeriod90: '90 days',
    releaseVersion: 'In which version',
    quarantineNote: 'What is disputed',

    closedByPublisher: 'closed by the publisher',

    cargoStateNew: 'New',
    cargoStateInWork: 'In work',
    cargoStateFixed: 'Done',
    cargoStateReleased: 'Released',
    cargoStateQuarantined: 'In quarantine',

    inviteStateWaiting: 'Waiting',
    inviteStateRedeemed: 'Redeemed',
    inviteStateExpired: 'Expired',
    inviteStateRevoked: 'Revoked',

    inviteCreate: 'Invite a project',
    inviteCreateTitle: 'An invitation to a project',
    inviteCreateName: 'The name of the future project',
    inviteCreateNameHint: 'By it the project will be seen in the lists. It cannot be changed later.',
    inviteCreateSubmit: 'Issue',
    inviteCreateWarn: 'The code appears here once: there will be nowhere to show it a second time.',
    inviteCreateCode: 'The code of the invitation',
    inviteCreateCopy: 'Copy',
    inviteCreateCopied: 'The code is copied',
    inviteCreateExpires: 'Valid until {{until}}',
    inviteCreateDone: 'The invitation for «{{name}}» is issued',
    inviteCreateFailed: 'The invitation could not be issued',
    inviteCreateClose: 'Close',
    inviteRevoke: 'Revoke',
    inviteRevokeTitle: 'Revoke the invitation',
    inviteRevokeQuestion: 'The invitation for «{{name}}» stops working. It cannot be brought back: the project will need a new one.',
    inviteRevokeDone: 'The invitation for «{{name}}» is revoked',
    inviteRevokeFailed: 'The invitation could not be revoked',

    panelClose: 'Close',

    listEmptyInvites: 'There are no invitations',
    listEmptyInvitesFrom: 'They are issued by the button «Invite a project» above the list',
    listEmpty: 'There are no records',
    listEmptyFrom: 'Not a single project has sent any yet',
    listEmptyByFilter: 'There are no records under this filter',
    listEmptyByFilterFrom: 'Drop the filter above the list or choose another value in it',
    listFailed: 'It could not be read',
    listSessionEnded: 'The session has ended: sign in again',
    listColumns: 'Set up the columns',
    listRefresh: 'Read anew',
    listRetry: 'Repeat',
    listIncident: 'Incident {{incident}}',

    detailsMissing: 'There is no record: it could have been deleted',
    detailsFailed: 'The record could not be read',
    detailsClose: 'Close',
    detailsPostmortem: 'The analysis of an incident',
    detailsProposal: 'Proposal',
    detailsText: 'Text',
    detailsFixNote: 'How it was fixed',
    detailsMonthRecord: 'The record of a month',
    detailsSummary: 'Digest',
    detailsSummaryMissing: 'There was no digest in this month: the record was created by another kind of cargo',
    detailsUsageSessions: 'Sessions',
    detailsSessionsMissing: 'Over the period not a single session loaded this skill',
    detailsSessionsFailed: 'The sessions could not be read',

    // Тексты отказов приёмника: ключ — код отказа общей либы.
    [ERefusal.InviteNameEmpty]: 'The issue awaits the name of the future project',
    [ERefusal.InviteProjectExists]: 'The project «{{name}}» already exists: it needs no invitation, and the name is taken',
    [ERefusal.InviteAlreadyIssued]: 'A valid invitation for «{{name}}» is already issued. Revoke it to issue a new one',
    [ERefusal.InviteNotFound]: 'There is no valid invitation for «{{name}}»',
    [ERefusal.InviteRejected]: 'The invitation is not accepted',
    [ERefusal.PostmortemNotFound]: 'There is no incident analysis with that sign',
    [ERefusal.ProposalNotFound]: 'There is no proposal with that sign',
    [ERefusal.SummaryNotFound]: 'There is no record of a month with that sign',
    [ERefusal.TreeUnknown]: 'The project with the sign «{{slug}}» is unknown to the message bus',
    [ERefusal.EnrollThrottled]: 'There are more requests from one client than the limit: wait and repeat',
    [ERefusal.EnrollMalformed]: 'The request awaits the code of an invitation and the sign of a project',
    [ERefusal.TreeTaken]: 'A project with that sign or that name already exists; the invitation is still valid',
    [ERefusal.SignInRequired]: 'The operation demands an entry',
    [ERefusal.RightRequired]: 'You have no right to this operation',
    [ERefusal.TreeTokenRequired]: 'The operation demands a token of a project',
    [ERefusal.TreeTokenRejected]: 'The token is not accepted',
    [ERefusal.AccessUndeclared]: 'The operation declared no access',
    [ERefusal.ChatSiteKeyEmpty]: 'The request awaits the key of the site',
    [ERefusal.ChatSiteRejected]: 'The key of the site is not accepted',
    [ERefusal.ChatOriginRejected]: 'The site accepts no requests from this address',
    [ERefusal.ChatConversationNotFound]: 'There is no conversation with that sign',
    [ERefusal.ChatTextEmpty]: 'A remark without a text is not accepted',
    [ERefusal.ChatTextTooLong]: 'The remark is longer than {{limit}} characters',
    [ERefusal.ChatThrottled]: 'There are more remarks from one visitor than {{limit}} per window: repeat in {{after}} s',
    [ERefusal.ChatStateUnknown]: 'The state of a conversation is expected as one of: live, closed',
    [ERefusal.ChatEntryRejected]: 'The page of the talks did not open',
    [ERefusal.ChatEntryStale]: 'The signature of the entry is stale',
    [ERefusal.ChatEntryExpired]: 'The entry is stale, refresh the page',
});
