import { RtKitLabelKey } from '../src/lib/i18n';

/**
 * Русские подписи кита — для витрины, не для пакета.
 *
 * Кит своего языка не знает: подписи ему даёт приложение функцией-переводчиком.
 * Витрина здесь и есть приложение, и её содержимое русское — без этого набора
 * собственные подписи кита встали бы английским умолчанием вперемешку с ним.
 *
 * Лежит рядом с витриной намеренно: потребителю кита формулировки этого
 * продукта не достаются.
 */
export const RT_KIT_LABELS_RU: Readonly<Record<RtKitLabelKey, string>> = {
    bottomSheetClose: 'Закрыть',
    chatAttachAria: 'Прикрепить файл',
    chatAttachTooltip: 'Прикрепить файл',
    chatAttachmentFallback: 'Вложение',
    chatCollapse: 'Свернуть чат',
    chatComposerAria: 'Поле ввода сообщения',
    chatDeleteAria: 'Удалить сообщение',
    chatDeleteTooltip: 'Удалить',
    chatDropOverlay: 'Отпустите файлы, чтобы прикрепить к сообщению',
    chatEmptyHint: 'Чат пока недоступен.',
    chatEmptyThread: 'Сообщений пока нет.',
    chatExpand: 'Развернуть чат на весь экран',
    chatMessageDeleted: 'Сообщение удалено',
    chatPlaceholder: 'Введите сообщение',
    chatRefreshAria: 'Обновить сообщения',
    chatRefreshTooltip: 'Обновить сообщения',
    chatRetryAria: 'Повторить отправку',
    chatRetryTooltip: 'Повторить',
    chatSendAria: 'Отправить сообщение',
    chatSendLabel: 'Отправить',
    chatStatusFailed: 'Не отправлено',
    chatStatusRead: 'Прочитано',
    chatStatusSending: 'Отправляется',
    chatStatusSent: 'Доставлено',
    chatTitle: 'Чат',
    counterDecrease: 'Уменьшить',
    counterIncrease: 'Увеличить',
    fieldErrorEmail: 'Некорректный email',
    fieldErrorMax: 'Значение слишком велико',
    fieldErrorMaxLength: 'Слишком длинное значение',
    fieldErrorMin: 'Значение слишком мало',
    fieldErrorMinLength: 'Слишком короткое значение',
    fieldErrorPattern: 'Некорректный формат',
    fieldErrorRequired: 'Обязательное поле',
    photoViewerClose: 'Закрыть просмотр',
    photoViewerNext: 'Следующее фото',
    photoViewerPrev: 'Предыдущее фото',
    themeToggleLabel: 'Переключить тему',
    uiActions: 'Действия',
    uiAuditEmptyHint: 'Здесь появятся события по сделке — переходы этапов и другие действия.',
    uiBack: 'Назад',
    uiBackToList: 'Назад к списку',
    uiBaseline: 'было {{value}}',
    uiCancel: 'Отмена',
    uiChangeAgent: 'Сменить агента',
    uiChooseFile: 'Выбрать файл',
    uiClear: 'Очистить',
    uiClose: 'Закрыть',
    uiCollapse: 'Свернуть',
    uiColumnLocked: 'Колонка закреплена',
    uiColumnSettings: 'Настройки колонок',
    uiColumnSettingsTitle: 'Настроить столбцы',
    uiCommentOptional: 'Комментарий (опционально)',
    uiConfirm: 'Подтвердить',
    uiConfirmAction: 'Подтверждение действия',
    uiContinue: 'Продолжить',
    uiCopied: 'Скопировано',
    uiCopy: 'Скопировать',
    uiCurrentStage: 'Текущий этап',
    uiDetails: 'Детали',
    uiDownload: 'Скачать',
    uiDownloadFile: 'Скачать: {{name}}',
    uiDragColumn: 'Перетащить колонку',
    uiFileDropOverlay: 'Отпустите файлы, чтобы прикрепить их',
    uiFilters: 'Фильтры',
    uiForward: 'Вперёд',
    uiHide: 'Скрыть',
    uiHideColumn: 'Скрыть колонку',
    uiHidePassword: 'Скрыть пароль',
    uiHint: 'Подсказка',
    uiHistory: 'История',
    uiInviteUser: 'Пригласить пользователя',
    uiItemsPerPage: 'Элементов на странице',
    uiLiveOnSite: 'Сейчас на сайте',
    uiLoadMore: 'Загрузить ещё',
    uiMainNav: 'Основная навигация',
    uiMore: 'Подробнее',
    uiMoreActions: 'Ещё действия',
    uiMoveStage: 'Перевести',
    uiMoveStageAria: 'Перевести этап',
    uiNavMenu: 'Меню навигации',
    uiNavUnread: 'Непросмотренное',
    uiNextPage: 'Следующая страница',
    uiNightGridAria: 'Сетка занятости',
    uiNoData: 'Пока нет данных',
    uiNoOptions: 'Нет вариантов',
    uiNoRows: 'Данных нет',
    uiNothingFound: 'Ничего не найдено',
    uiNotifications: 'Уведомления',
    uiPageOf: 'Стр. {{page}} из {{last}}',
    uiPagination: 'Постраничная навигация',
    uiPerPage: 'На странице:',
    uiPickAgent: 'Выберите агента',
    uiPickAnotherAgent: 'Выберите другого агента',
    uiPickTransition: 'Выберите переход',
    uiPrevPage: 'Предыдущая страница',
    uiProfile: 'Профиль',
    uiRangeEmpty: '0 из 0',
    uiRangeOf: '{{from}}–{{to}} из {{total}}',
    uiRemove: 'Удалить',
    uiRename: 'Переименовать',
    uiReplace: 'Заменить',
    uiReplaceAgentTitle: 'Заменить агента',
    uiResetDefaults: 'Сбросить к умолчанию',
    uiResizeDetails: 'Изменить ширину деталей',
    uiResizeList: 'Изменить ширину списка',
    uiRevert: 'Отменить',
    uiSave: 'Сохранить',
    uiSaveNewAgent: 'Сохранить нового агента',
    uiSearch: 'Поиск',
    uiSectionInProgress: '{{label}} — раздел в разработке',
    uiSelectValues: 'Выберите значения',
    uiShow: 'Показать',
    uiShowColumn: 'Показать колонку',
    uiShowDetails: 'Показать детали',
    uiShowPassword: 'Показать пароль',
    uiStageNoteHint: 'Внутренняя заметка — клиенту не видна.',
    uiStageTransition: 'Переход этапа',
    uiSubscribeNotifications: 'Подписаться на уведомления',
    uiTabInvalid: 'Вкладка содержит ошибки',
    uiTargetStage: 'Целевой этап',
    uiTargetStageRequired: 'Выберите целевой этап.',
    uiThreadListEmptyHint: 'Здесь появятся новые треды.',
    uiToList: 'К списку',
    uiUnsavedDiscard: 'Закрыть без сохранения',
    uiUnsavedMessage: 'В панели есть правки, которые ещё не сохранены. Выберите, что с ними сделать.',
    uiUnsavedSave: 'Сохранить и закрыть',
    uiUnsavedStay: 'Остаться',
    uiUnsavedTitle: 'Несохранённые правки',
    uiWelcomeAria: 'Приветствие нового пользователя',
    uiYearOverYear: 'г/г',
};
