import { TRtKitLabelKey } from '../src/lib/i18n';

/**
 * Русские подписи кита — для витрины, не для пакета.
 *
 * Кит своего языка не знает: подписи ему даёт приложение функцией-переводчиком.
 * Витрина здесь и есть приложение, и её содержимое русское — без этого набора
 * собственные подписи кита встали бы английским умолчанием вперемешку с ним.
 *
 * Лежит рядом с витриной намеренно: потребителю кита формулировки этого
 * продукта не достаются.
 */
export const RT_KIT_LABELS_RU: Readonly<Record<TRtKitLabelKey, string>> = {
    bottomSheetClose: 'Закрыть',
    chatAttachAria: 'Прикрепить файл',
    chatAttachTooltip: 'Прикрепить файл',
    chatAttachmentFallback: 'Вложение',
    chatCollapse: 'Свернуть чат',
    chatComposerAria: 'Поле ввода сообщения',
    chatComposerHint: 'Enter — отправить, Shift + Enter — новая строка',
    chatDeleteAria: 'Удалить сообщение',
    chatDeleteTooltip: 'Удалить',
    chatDropOverlay: 'Отпустите файлы, чтобы прикрепить к сообщению',
    chatEmptyHint: 'Чат пока недоступен.',
    chatEmptyThread: 'Сообщений пока нет.',
    chatExpand: 'Развернуть чат на весь экран',
    chatMessageDeleted: 'Сообщение удалено',
    chatPlaceholder: 'Введите сообщение',
    chatRefreshAria: 'Обновить сообщения',
    chatRefreshTooltip: 'Обновить сообщения',
    chatRetryAria: 'Повторить отправку',
    chatRetryTooltip: 'Повторить',
    chatSendAria: 'Отправить сообщение',
    chatSendLabel: 'Отправить',
    chatStatusFailed: 'Не отправлено',
    chatStatusRead: 'Прочитано',
    chatStatusSending: 'Отправляется',
    chatStatusSent: 'Доставлено',
    chatTitle: 'Чат',
    counterDecrease: 'Уменьшить',
    counterIncrease: 'Увеличить',
    dataListClearFilters: 'Снять отбор',
    dataListHorizontalScrollbar: 'Показывать полосу прокрутки по горизонтали',
    dataListPlaceholder: 'Записей нет',
    dataListRefresh: 'Обновить',
    dataListSearchPlaceholder: 'Поиск...',
    dataListSelectAll: 'Отметить все',
    dataListSelected: 'Отмечено: {{count}}',
    dataListSettingsHint: 'Порядок и видимость колонок, полосы прокрутки',
    dataListSettingsTitle: 'Настройка таблицы',
    dataListTableConfig: 'Настроить колонки',
    dataListVerticalScrollbar: 'Показывать полосу прокрутки по вертикали',
    dataTableActions: 'Действия',
    dataTableCopied: 'Скопировано',
    dataTableCopy: 'Скопировать',
    dataTableFilterClear: 'Очистить условие',
    dataTableFilterOperatorContains: 'Содержит',
    dataTableFilterOperatorEquals: 'Равно',
    dataTableFilterOperatorGreaterThan: 'Больше',
    dataTableFilterOperatorLessThan: 'Меньше',
    dataTableFilterOperatorNotEquals: 'Не равно',
    dataTableFilterSelectPlaceholder: 'Выберите значение',
    dataTableFilterValuePlaceholder: 'Введите значение',
    dataTableSelectPage: 'Отметить строки этой страницы',
    dataTableSelectRow: 'Отметить строку',
    fieldErrorEmail: 'Некорректный email',
    fieldErrorMax: 'Значение слишком велико',
    fieldErrorMaxLength: 'Слишком длинное значение',
    fieldErrorMin: 'Значение слишком мало',
    fieldErrorMinLength: 'Слишком короткое значение',
    fieldErrorPattern: 'Некорректный формат',
    fieldErrorRequired: 'Обязательное поле',
    photoViewerClose: 'Закрыть просмотр',
    photoViewerNext: 'Следующее фото',
    photoViewerPrev: 'Предыдущее фото',
    themeToggleLabel: 'Переключить тему',
    uiActions: 'Действия',
    uiApply: 'Применить',
    uiAuditEmptyHint: 'Здесь появятся события по сделке — переходы этапов и другие действия.',
    uiBack: 'Назад',
    uiBackToList: 'Назад к списку',
    uiBaseline: 'было {{value}}',
    uiCancel: 'Отмена',
    uiChangeAgent: 'Сменить агента',
    uiChooseFile: 'Выбрать файл',
    uiChooseMonth: 'Выбрать месяц и год',
    uiClear: 'Очистить',
    uiClearFilters: 'Сбросить отбор',
    uiClose: 'Закрыть',
    uiCollapse: 'Свернуть',
    uiColumnLocked: 'Колонка закреплена',
    uiColumnSettings: 'Настройки колонок',
    uiColumnSettingsTitle: 'Настроить столбцы',
    uiCommentOptional: 'Комментарий (опционально)',
    uiConfirm: 'Подтвердить',
    uiConfirmAction: 'Подтверждение действия',
    uiContinue: 'Продолжить',
    uiCopied: 'Скопировано',
    uiCopy: 'Скопировать',
    uiCurrentStage: 'Текущий этап',
    uiDate: 'Дата',
    uiDaysFew: '{{count}} дня',
    uiDaysMany: '{{count}} дней',
    uiDaysOne: '{{count}} день',
    uiDaysOther: '{{count}} дня',
    uiDetails: 'Детали',
    uiDiscardChanges: 'Отменить изменения',
    uiDone: 'Готово',
    uiDownload: 'Скачать',
    uiDownloadFile: 'Скачать: {{name}}',
    uiDragColumn: 'Перетащить колонку',
    uiExpand: 'Развернуть',
    uiFileDropOverlay: 'Отпустите файлы, чтобы прикрепить их',
    uiFilterChoose: 'Выберите',
    uiFilterContains: 'Содержит',
    uiFilterEndsWith: 'Заканчивается на',
    uiFilterEquals: 'Равно',
    uiFilterGreaterThan: 'Больше',
    uiFilterLessThan: 'Меньше',
    uiFilterNotEquals: 'Не равно',
    uiFilterStartsWith: 'Начинается с',
    uiFilterValue: 'Значение отбора',
    uiFilters: 'Фильтры',
    uiForward: 'Вперёд',
    uiHide: 'Скрыть',
    uiHideColumn: 'Скрыть колонку',
    uiHidePassword: 'Скрыть пароль',
    uiHint: 'Подсказка',
    uiHistory: 'История',
    uiHours: 'Часы',
    uiInviteUser: 'Пригласить пользователя',
    uiItemsPerPage: 'Элементов на странице',
    uiLast30Days: 'Последние 30 дней',
    uiLast7Days: 'Последние 7 дней',
    uiLastMonth: 'Прошлый месяц',
    uiLiveOnSite: 'Сейчас на сайте',
    uiLoadMore: 'Загрузить ещё',
    uiMainNav: 'Основная навигация',
    uiMinutes: 'Минуты',
    uiMore: 'Подробнее',
    uiMoreActions: 'Ещё действия',
    uiMoveStage: 'Перевести',
    uiMoveStageAria: 'Перевести этап',
    uiNavMenu: 'Меню навигации',
    uiNavUnread: 'Непросмотренное',
    uiNextMonth: 'Следующий месяц',
    uiNextPage: 'Следующая страница',
    uiNextYear: 'Следующий год',
    uiNightGridAria: 'Сетка занятости',
    uiNoData: 'Пока нет данных',
    uiNoOptions: 'Нет вариантов',
    uiNoRows: 'Данных нет',
    uiNothingFound: 'Ничего не найдено',
    uiNotifications: 'Уведомления',
    uiNow: 'Сейчас',
    uiOpenCalendar: 'Открыть календарь',
    uiPageOf: 'Стр. {{page}} из {{last}}',
    uiPagination: 'Постраничная навигация',
    uiPerPage: 'На странице:',
    uiPeriod: 'Период',
    uiPickAgent: 'Выберите агента',
    uiPickAnotherAgent: 'Выберите другого агента',
    uiPickEndDate: 'Выберите дату окончания',
    uiPickStartDate: 'Выберите дату начала',
    uiPickTransition: 'Выберите переход',
    uiPrevMonth: 'Предыдущий месяц',
    uiPrevPage: 'Предыдущая страница',
    uiPrevYear: 'Предыдущий год',
    uiProfile: 'Профиль',
    uiQuickRanges: 'Быстрый выбор',
    uiRangeEmpty: '0 из 0',
    uiRangeOf: '{{from}}–{{to}} из {{total}}',
    uiRemove: 'Удалить',
    uiRename: 'Переименовать',
    uiReplace: 'Заменить',
    uiReplaceAgentTitle: 'Заменить агента',
    uiReset: 'Сбросить',
    uiResetDefaults: 'Сбросить к умолчанию',
    uiResizeDetails: 'Изменить ширину деталей',
    uiResizeList: 'Изменить ширину списка',
    uiRefresh: 'Обновить',
    uiRevert: 'Отменить',
    uiSave: 'Сохранить',
    uiSaveNewAgent: 'Сохранить нового агента',
    uiScrollDown: 'Прокрутить вниз',
    uiSearch: 'Поиск',
    uiSectionInProgress: '{{label}} — раздел в разработке',
    uiSelectAll: 'Выбрать все',
    uiSelectValues: 'Выберите значения',
    uiSelectedCount: 'Выбрано: {{count}}',
    uiSelectedOf: 'Выбрано: {{count}} из {{total}}',
    uiShapeDay: 'дд',
    uiShapeHour: 'чч',
    uiShapeMinute: 'мм',
    uiShapeMonth: 'мм',
    uiShapeYear: 'гггг',
    uiShow: 'Показать',
    uiShowColumn: 'Показать колонку',
    uiShowDetails: 'Показать детали',
    uiShowPassword: 'Показать пароль',
    uiStageNoteHint: 'Внутренняя заметка — клиенту не видна.',
    uiStageTransition: 'Переход этапа',
    uiSubscribeNotifications: 'Подписаться на уведомления',
    uiTabInvalid: 'Вкладка содержит ошибки',
    uiTargetStage: 'Целевой этап',
    uiTargetStageRequired: 'Выберите целевой этап.',
    uiThisMonth: 'Этот месяц',
    uiThreadListEmptyHint: 'Здесь появятся новые треды.',
    uiTime: 'Время',
    uiToList: 'К списку',
    uiToday: 'Сегодня',
    uiUnsavedDiscard: 'Закрыть без сохранения',
    uiUnsavedMessage: 'В панели есть правки, которые ещё не сохранены. Выберите, что с ними сделать.',
    uiUnsavedSave: 'Сохранить и закрыть',
    uiUnsavedStay: 'Остаться',
    uiUnsavedTitle: 'Несохранённые правки',
    uiWelcomeAria: 'Приветствие нового пользователя',
    uiYearOverYear: 'г/г',
    uiYesterday: 'Вчера',
};
