import { EBookingMailBadge, EBookingSource, EBookingStatus, IBooking } from './booking.model';

/**
 * Правдоподобные заявки для демонстрационного экрана. Пустого набора здесь нет намеренно:
 * история, рисующая пустую таблицу, покрытием не считается — она показывает рамку и ни одного
 * состояния строки.
 *
 * Набор подобран так, чтобы в таблице разом стояли все состояния заявки, все исходы писем и обе
 * ветки каждой ячейки: строка без почты, строка без мессенджера, строка без суммы, строка без
 * имени гостя. Иначе половина разметки таблицы на экране не показывается вовсе.
 *
 * Даты записаны абсолютными, а не считаются от сегодняшнего дня: снимок, снятый с плавающих дат,
 * расходится с эталоном каждые сутки.
 *
 * Записей больше, чем помещается на странице: переключатель страниц кит показывает только там,
 * где список не умещается в наименьший размер страницы, и на коротком наборе экран остался бы
 * без него вовсе.
 */

/**
 * Объекты, на которые заводят брони. Перечислением, а не строками по месту: их называет и
 * колонка таблицы, и выпадающий список панели, и каждая запись набора.
 */
export enum EShowcaseProperty {
    Lotus = 'villa-lotus',
    Coral = 'villa-coral',
    Monsoon = 'villa-monsoon',
    Harbour = 'apart-harbour',
}

/** Подписи объектов для выпадающего списка и колонки таблицы. */
export const SHOWCASE_PROPERTIES: ReadonlyArray<{ readonly id: EShowcaseProperty; readonly label: string }> = [
    { id: EShowcaseProperty.Lotus, label: 'Вилла «Лотос»' },
    { id: EShowcaseProperty.Coral, label: 'Вилла «Коралл»' },
    { id: EShowcaseProperty.Monsoon, label: 'Вилла «Муссон»' },
    { id: EShowcaseProperty.Harbour, label: 'Апартаменты «Гавань»' },
];

export const SHOWCASE_BOOKINGS: ReadonlyArray<IBooking.State> = [
    {
        id: 'bk-1041',
        number: 1041,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-09-04',
        checkOut: '2026-09-11',
        guestName: 'Анна Северова',
        guestEmail: 'a.severova@example.com',
        guestMessenger: '@severova',
        adults: 2,
        children: 1,
        source: EBookingSource.Site,
        status: EBookingStatus.Pending,
        totalThb: 84000,
        comment: 'Просит детскую кровать и поздний заезд.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1040',
        number: 1040,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-09-02',
        checkOut: '2026-09-09',
        guestName: 'Marek Nowak',
        guestEmail: 'marek.nowak@example.com',
        guestMessenger: '',
        adults: 2,
        children: 0,
        source: EBookingSource.Booking,
        status: EBookingStatus.Confirmed,
        totalThb: 96500,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1039',
        number: 1039,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-08-28',
        checkOut: '2026-09-03',
        guestName: 'Ирина Гладкова',
        guestEmail: '',
        guestMessenger: '@gladkova_i',
        adults: 4,
        children: 2,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Confirmed,
        totalThb: 152000,
        comment: 'Две семьи, просят трансфер из аэропорта.',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1038',
        number: 1038,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-08-25',
        checkOut: '2026-08-27',
        guestName: 'Tomás Ferreira',
        guestEmail: 't.ferreira@example.com',
        guestMessenger: '',
        adults: 1,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Даты заняты другой бронью.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1037',
        number: 1037,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-08-20',
        checkOut: '2026-08-30',
        guestName: 'Сергей Панин',
        guestEmail: 's.panin@example.com',
        guestMessenger: '@panin',
        adults: 2,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Cancelled,
        totalThb: 118000,
        comment: 'Отменил за две недели, вернули предоплату.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1036',
        number: 1036,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-10-12',
        checkOut: '2026-10-19',
        guestName: '',
        guestEmail: 'guest-1036@example.com',
        guestMessenger: '',
        adults: 3,
        children: 0,
        source: EBookingSource.Vrbo,
        status: EBookingStatus.Pending,
        totalThb: 0,
        comment: '',
        mailBadge: EBookingMailBadge.Pending,
    },
    {
        id: 'bk-1035',
        number: 1035,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-10-01',
        checkOut: '2026-10-08',
        guestName: 'Laura Bianchi',
        guestEmail: 'l.bianchi@example.com',
        guestMessenger: '@bianchi',
        adults: 2,
        children: 2,
        source: EBookingSource.Site,
        status: EBookingStatus.Pending,
        totalThb: 143000,
        comment: 'Годовщина, просит украсить спальню.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1034',
        number: 1034,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-09-18',
        checkOut: '2026-09-22',
        guestName: 'Дмитрий Ковалёв',
        guestEmail: 'd.kovalev@example.com',
        guestMessenger: '',
        adults: 1,
        children: 0,
        source: EBookingSource.Booking,
        status: EBookingStatus.Confirmed,
        totalThb: 41000,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1033',
        number: 1033,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-11-02',
        checkOut: '2026-11-12',
        guestName: 'Hannah Weiss',
        guestEmail: 'h.weiss@example.com',
        guestMessenger: '@hweiss',
        adults: 2,
        children: 1,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Pending,
        totalThb: 127500,
        comment: 'Спрашивает про аренду скутера.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1032',
        number: 1032,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-07-30',
        checkOut: '2026-08-06',
        guestName: 'Олег Тарасов',
        guestEmail: 'o.tarasov@example.com',
        guestMessenger: '',
        adults: 5,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Cancelled,
        totalThb: 89000,
        comment: '',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1031',
        number: 1031,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-12-24',
        checkOut: '2027-01-04',
        guestName: 'Yuki Tanaka',
        guestEmail: 'y.tanaka@example.com',
        guestMessenger: '@yuki_t',
        adults: 2,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Confirmed,
        totalThb: 268000,
        comment: 'Новогодние даты, полная предоплата.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1030',
        number: 1030,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-09-26',
        checkOut: '2026-09-29',
        guestName: 'Мария Ильина',
        guestEmail: '',
        guestMessenger: '@ilyina_m',
        adults: 2,
        children: 0,
        source: EBookingSource.Site,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Объект на ремонте.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1029',
        number: 1029,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-10-24',
        checkOut: '2026-10-31',
        guestName: 'Павел Ершов',
        guestEmail: 'p.ershov@example.com',
        guestMessenger: '',
        adults: 2,
        children: 2,
        source: EBookingSource.Booking,
        status: EBookingStatus.Pending,
        totalThb: 134000,
        comment: 'Просит две детские кровати.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1028',
        number: 1028,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-11-15',
        checkOut: '2026-11-21',
        guestName: 'Elena Popescu',
        guestEmail: 'e.popescu@example.com',
        guestMessenger: '@epopescu',
        adults: 3,
        children: 1,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Confirmed,
        totalThb: 112000,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1027',
        number: 1027,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-08-14',
        checkOut: '2026-08-18',
        guestName: 'Никита Жуков',
        guestEmail: '',
        guestMessenger: '@zhukov',
        adults: 1,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Cancelled,
        totalThb: 52000,
        comment: 'Перенёс поездку на весну.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1026',
        number: 1026,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-12-05',
        checkOut: '2026-12-12',
        guestName: 'Sofia Marino',
        guestEmail: 's.marino@example.com',
        guestMessenger: '',
        adults: 2,
        children: 0,
        source: EBookingSource.Vrbo,
        status: EBookingStatus.Pending,
        totalThb: 97000,
        comment: 'Спрашивает про поздний выезд.',
        mailBadge: EBookingMailBadge.Pending,
    },
    {
        id: 'bk-1025',
        number: 1025,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-09-12',
        checkOut: '2026-09-16',
        guestName: 'Алина Ковач',
        guestEmail: 'a.kovach@example.com',
        guestMessenger: '@kovach_a',
        adults: 2,
        children: 0,
        source: EBookingSource.Site,
        status: EBookingStatus.Confirmed,
        totalThb: 68000,
        comment: '',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1024',
        number: 1024,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-10-05',
        checkOut: '2026-10-09',
        guestName: '',
        guestEmail: 'guest-1024@example.com',
        guestMessenger: '',
        adults: 4,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Объект занят на эти даты.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1023',
        number: 1023,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-11-26',
        checkOut: '2026-12-03',
        guestName: 'Игорь Белов',
        guestEmail: 'i.belov@example.com',
        guestMessenger: '@belov',
        adults: 2,
        children: 1,
        source: EBookingSource.Booking,
        status: EBookingStatus.Pending,
        totalThb: 121500,
        comment: 'Просит счёт на организацию.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1022',
        number: 1022,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-07-18',
        checkOut: '2026-07-25',
        guestName: 'Klara Novak',
        guestEmail: 'k.novak@example.com',
        guestMessenger: '',
        adults: 2,
        children: 2,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Confirmed,
        totalThb: 88000,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1021',
        number: 1021,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2027-01-09',
        checkOut: '2027-01-16',
        guestName: 'Роман Гущин',
        guestEmail: '',
        guestMessenger: '@gushchin',
        adults: 5,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Pending,
        totalThb: 0,
        comment: 'Компания друзей, ждут расчёт.',
        mailBadge: EBookingMailBadge.Pending,
    },
    {
        id: 'bk-1020',
        number: 1020,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-08-08',
        checkOut: '2026-08-12',
        guestName: 'Marta Sanchez',
        guestEmail: 'm.sanchez@example.com',
        guestMessenger: '@msanchez',
        adults: 1,
        children: 0,
        source: EBookingSource.Vrbo,
        status: EBookingStatus.Cancelled,
        totalThb: 46000,
        comment: '',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1019',
        number: 1019,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-09-05',
        checkOut: '2026-09-10',
        guestName: 'Ольга Терентьева',
        guestEmail: 'o.terenteva@example.com',
        guestMessenger: '',
        adults: 2,
        children: 1,
        source: EBookingSource.Site,
        status: EBookingStatus.Confirmed,
        totalThb: 105000,
        comment: 'Заезд ночью, предупредила охрану.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1018',
        number: 1018,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-10-17',
        checkOut: '2026-10-20',
        guestName: 'Adam Kowalczyk',
        guestEmail: 'a.kowalczyk@example.com',
        guestMessenger: '@akowal',
        adults: 2,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Отказ: объект на плановом обслуживании.',
        mailBadge: EBookingMailBadge.None,
    },
];
