import { EBookingMailBadge, EBookingSource, EBookingStatus, IBooking } from './booking.model';

/**
 * Правдоподобные заявки для демонстрационного экрана. Пустого набора здесь нет намеренно:
 * история, рисующая пустую таблицу, покрытием не считается — она показывает рамку и ни одного
 * состояния строки.
 *
 * Набор подобран так, чтобы в таблице разом стояли все состояния заявки, все исходы писем и обе
 * ветки каждой ячейки: строка без почты, строка без мессенджера, строка без суммы, строка без
 * имени гостя. Иначе половина разметки таблицы на экране не показывается вовсе.
 *
 * Даты записаны абсолютными, а не считаются от сегодняшнего дня: снимок, снятый с плавающих дат,
 * расходится с эталоном каждые сутки.
 */

/**
 * Объекты, на которые заводят брони. Перечислением, а не строками по месту: их называет и
 * колонка таблицы, и выпадающий список панели, и каждая запись набора.
 */
export enum EShowcaseProperty {
    Lotus = 'villa-lotus',
    Coral = 'villa-coral',
    Monsoon = 'villa-monsoon',
    Harbour = 'apart-harbour',
}

/** Подписи объектов для выпадающего списка и колонки таблицы. */
export const SHOWCASE_PROPERTIES: ReadonlyArray<{ readonly id: EShowcaseProperty; readonly label: string }> = [
    { id: EShowcaseProperty.Lotus, label: 'Вилла «Лотос»' },
    { id: EShowcaseProperty.Coral, label: 'Вилла «Коралл»' },
    { id: EShowcaseProperty.Monsoon, label: 'Вилла «Муссон»' },
    { id: EShowcaseProperty.Harbour, label: 'Апартаменты «Гавань»' },
];

export const SHOWCASE_BOOKINGS: ReadonlyArray<IBooking.State> = [
    {
        id: 'bk-1041',
        number: 1041,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-09-04',
        checkOut: '2026-09-11',
        guestName: 'Анна Северова',
        guestEmail: 'a.severova@example.com',
        guestMessenger: '@severova',
        adults: 2,
        children: 1,
        source: EBookingSource.Site,
        status: EBookingStatus.Pending,
        totalThb: 84000,
        comment: 'Просит детскую кровать и поздний заезд.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1040',
        number: 1040,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-09-02',
        checkOut: '2026-09-09',
        guestName: 'Marek Nowak',
        guestEmail: 'marek.nowak@example.com',
        guestMessenger: '',
        adults: 2,
        children: 0,
        source: EBookingSource.Booking,
        status: EBookingStatus.Confirmed,
        totalThb: 96500,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1039',
        number: 1039,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-08-28',
        checkOut: '2026-09-03',
        guestName: 'Ирина Гладкова',
        guestEmail: '',
        guestMessenger: '@gladkova_i',
        adults: 4,
        children: 2,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Confirmed,
        totalThb: 152000,
        comment: 'Две семьи, просят трансфер из аэропорта.',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1038',
        number: 1038,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-08-25',
        checkOut: '2026-08-27',
        guestName: 'Tomás Ferreira',
        guestEmail: 't.ferreira@example.com',
        guestMessenger: '',
        adults: 1,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Даты заняты другой бронью.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1037',
        number: 1037,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-08-20',
        checkOut: '2026-08-30',
        guestName: 'Сергей Панин',
        guestEmail: 's.panin@example.com',
        guestMessenger: '@panin',
        adults: 2,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Cancelled,
        totalThb: 118000,
        comment: 'Отменил за две недели, вернули предоплату.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1036',
        number: 1036,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-10-12',
        checkOut: '2026-10-19',
        guestName: '',
        guestEmail: 'guest-1036@example.com',
        guestMessenger: '',
        adults: 3,
        children: 0,
        source: EBookingSource.Vrbo,
        status: EBookingStatus.Pending,
        totalThb: 0,
        comment: '',
        mailBadge: EBookingMailBadge.Pending,
    },
    {
        id: 'bk-1035',
        number: 1035,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-10-01',
        checkOut: '2026-10-08',
        guestName: 'Laura Bianchi',
        guestEmail: 'l.bianchi@example.com',
        guestMessenger: '@bianchi',
        adults: 2,
        children: 2,
        source: EBookingSource.Site,
        status: EBookingStatus.Pending,
        totalThb: 143000,
        comment: 'Годовщина, просит украсить спальню.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1034',
        number: 1034,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-09-18',
        checkOut: '2026-09-22',
        guestName: 'Дмитрий Ковалёв',
        guestEmail: 'd.kovalev@example.com',
        guestMessenger: '',
        adults: 1,
        children: 0,
        source: EBookingSource.Booking,
        status: EBookingStatus.Confirmed,
        totalThb: 41000,
        comment: '',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1033',
        number: 1033,
        propertyId: EShowcaseProperty.Lotus,
        checkIn: '2026-11-02',
        checkOut: '2026-11-12',
        guestName: 'Hannah Weiss',
        guestEmail: 'h.weiss@example.com',
        guestMessenger: '@hweiss',
        adults: 2,
        children: 1,
        source: EBookingSource.Airbnb,
        status: EBookingStatus.Pending,
        totalThb: 127500,
        comment: 'Спрашивает про аренду скутера.',
        mailBadge: EBookingMailBadge.None,
    },
    {
        id: 'bk-1032',
        number: 1032,
        propertyId: EShowcaseProperty.Coral,
        checkIn: '2026-07-30',
        checkOut: '2026-08-06',
        guestName: 'Олег Тарасов',
        guestEmail: 'o.tarasov@example.com',
        guestMessenger: '',
        adults: 5,
        children: 0,
        source: EBookingSource.Direct,
        status: EBookingStatus.Cancelled,
        totalThb: 89000,
        comment: '',
        mailBadge: EBookingMailBadge.Failed,
    },
    {
        id: 'bk-1031',
        number: 1031,
        propertyId: EShowcaseProperty.Monsoon,
        checkIn: '2026-12-24',
        checkOut: '2027-01-04',
        guestName: 'Yuki Tanaka',
        guestEmail: 'y.tanaka@example.com',
        guestMessenger: '@yuki_t',
        adults: 2,
        children: 0,
        source: EBookingSource.Agoda,
        status: EBookingStatus.Confirmed,
        totalThb: 268000,
        comment: 'Новогодние даты, полная предоплата.',
        mailBadge: EBookingMailBadge.Sent,
    },
    {
        id: 'bk-1030',
        number: 1030,
        propertyId: EShowcaseProperty.Harbour,
        checkIn: '2026-09-26',
        checkOut: '2026-09-29',
        guestName: 'Мария Ильина',
        guestEmail: '',
        guestMessenger: '@ilyina_m',
        adults: 2,
        children: 0,
        source: EBookingSource.Site,
        status: EBookingStatus.Rejected,
        totalThb: 0,
        comment: 'Объект на ремонте.',
        mailBadge: EBookingMailBadge.Sent,
    },
];
