name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    main:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.12.0]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            # Cache node_modules
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile

            - run: pnpm run build
