name: Publish to npm

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Specify version: patch, minor, major, or specific version (e.g. 1.2.3)'
                required: true
                default: 'patch'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.12.0]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.6.3
                  run_install: false

            - name: Cache node_modules
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile
                  sudo apt-get install jq

            - name: Update version
              run: |
                  node update-version.cjs ${{ github.event.inputs.version }}
                  pnpm run changelog:tools
                  VERSION=$(jq -r .version projects/tools/package.json)
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: 'chore: bump version to ${{ env.VERSION }} [ci skip]'

            - name: Build
              run: pnpm run build

            - name: Publish
              run: pnpm run packagr:tools
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
