name: Publish to npm

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            version:
                description: 'Specify the version (patch, minor, major, or a specific version)'
                required: true
                default: 'patch'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.12.0]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: false

            - name: Cache node_modules
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile
                  sudo apt-get install jq

            - name: Update version
              run: |
                  cd projects/tools
                  pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
                  echo "Updated package.json:"
                  cat package.json
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add package.json
                  git commit -m "chore: bump version to $(jq -r .version package.json) [ci skip]" || echo "Nothing to commit"
                  git push
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: pnpm run build

            - name: Publish
              run: pnpm run packagr:tools
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
